# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  
  desc "Run all tests"
  lane :test do
    run_tests(
      scheme: "MovieBrowser",
      devices: ["iPhone 15"],
      clean: true
    )
  end
  
  desc "Deploy to TestFlight"
  lane :deploy do
    # 自動遞增 build number
    increment_build_number(
      build_number: latest_testflight_build_number + 1
    )
    
    # Build
    build_app(
      scheme: "MovieBrowser",
      configuration: "Release",
      export_method: "app-store"
    )
    
    # 上傳到 TestFlight
    upload_to_testflight(
      api_key_path: "fastlane/api_key.json",
      skip_waiting_for_build_processing: true
    )
  end
end
